# Secret Manager for Cloud SQL Password
resource "google_secret_manager_secret" "cloud_sql_password" {
  secret_id = "${local.resource_prefix}-db-password"

  labels = merge(
    local.common_labels,
    {
      "secret-type" = "database-password"
    }
  )

  replication {
    automatic = true
  }
}

# NOTE: In production, generate a strong random password
# For now, this is a placeholder that must be manually created or generated by CI/CD
resource "google_secret_manager_secret_version" "cloud_sql_password" {
  secret      = google_secret_manager_secret.cloud_sql_password.id
  secret_data = random_password.cloud_sql_password.result
}

# Generate a random password for Cloud SQL
resource "random_password" "cloud_sql_password" {
  length  = 32
  special = true
}

# Grant Cloud Run service account access to the secret
resource "google_secret_manager_secret_iam_member" "cloud_run_access" {
  secret_id = google_secret_manager_secret.cloud_sql_password.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.cloud_run_sa.email}"
}

# Output the generated password (marked sensitive)
output "cloud_sql_password" {
  description = "Generated Cloud SQL password (STORE SECURELY)"
  value       = random_password.cloud_sql_password.result
  sensitive   = true
}
